Submodule pqxx fb1cca3d..c23b5a09:
> Tidy up prepared statements docs.
> Generalize floating-point conversion tests.
> Comment.
> Fix MSVC error C2487: member of dll interface class may not be
declared with dll interface. (#40)
> Rename DirectExec.
> Rename more.
> Rename more old-style function names.
> Rename CmdStatus.
> Test binarystring in prepared statement.
> Rename Exec() to exec().
> Update docs, remove TODO comments.
> Documentation.
> C++11-style prepared and parameterised statements!
> Regenerate on Ubuntu 17.10.
> Skip result operator=() on self-assignment.
> Fix link order in README.md.
> Retire unnecessary connection capabilities.
> Lower-case output on dot check.
> Use AX_GCC_CONST_CALL for "const" attribute check.
> Regenerate on Ubuntu 17.10.
> Always pass -Wformat=2 for gcc or clang.
> Remove redundant gcc flags in maintainer mode.
> Add missing export.
> Fix clang signedness errors in row/field numbers.
> Make field contain a copy of its result.
> Further decouple row and field from result.
> Document some macros.
> Fix underflow in reverse row iterator.
> Typo in comment.
> Fix underflow in reverse result iterator.
> Cast fd to SOCKET for WSAPoll().
> Fix some WSAPoll() compile errors.
> Fix perf warning on bool conversion.
> Add sample headers for gcc 7.2.
> Regenerate on Ubuntu 17.10.
> Re-do poll()/select() support.  Add WSAPoll().
> No, explicit does not work for that constructor!
> Merge branch 'master' of github.com:jtv/libpqxx
> Explicit const_result_iterator(const row&).
> Enable some more gcc warnings.
> Ignore autoconf-generated temp files.
> Don't alias select() arguments.
> Add new gcc warning options in maintainer mode.
> Replace some 0 with nullptr.
> Replace some 0 with nullptr.
> Mark member function as override.
> NEWS: Note exec0, exec1 etc.
> Fix silly documentation mistake.
> Regenerate on Ubuntu 17.10.
> Fix broken "make dist."
> Replace some 'const char[]' with constexpr.
> Extract documentation, reduce export surface.
> Extract main documentation into its own header.
> Modernise a few more headers.
> Only check for socket lib if we need select().
> Leave C++11 check to autoconf-archive entirely.
> Regenerate on Ubuntu 17.10.
> NEWS: Faster configure.
> Don't need select() if there's poll().
> Fail without poll() or select().
> Drop std::unary_function/std::binary_function.
> Regenerate on Ubuntu 17.04.
> Don't check for C compiler.
> Reorder configure checks; remove AC_HEADER_STDC.
> Simplify configure.ac a bit more.
> Fix compile error in Windows code (part of #34).
> Missing configure output message.
> Simpler rmlo through lambdas.
> Simpler separted_list through lambdas.
> Note in isolation level docs.
> Retire obsolete thread-safety checks.
> Hide a private largeobject member.
> Use nproc, not /proc/cpuinfo.
> Always write old test names with two digits.
> Rename old tests: never quite needed 3 digits!
> Regenerate on Ubuntu 17.04.
> Get largeobject errors from connection.
> Note NOMINMAX change in NEWS.
> Stop defining NOMINMAX for Visual Studio.
> Replace some defines with constexpr.
> Don't use strlcpy().
> Document namedclass.
> Missed a file in commit.
> Mention new transactor in NEWS.
> New, simpler, lambda-friendly transactor framework.
> No longer need space in template "> >".
> Enable out-of-tree doc builds.
> Export internal::clear_result.
> Out-of-tree builds work now!  Fixes #29.
> Fix extract_version, lint for out-of-tree builds.
> Fix splitconfig for out-of-tree builds.
> Speedup from_string_float, to_string_fallback by using
std::locale::classic() instead of std::locale("C") (#28)
> Check for C++11 support; may need autoconf-archive.